// 旅行先診断や候補検索で使う旅行先マスターデータ。
export const destinationCatalog = [
  {
    id: 'kyoto',
    name: '京都',
    country: '日本',
    area: '関西',
    tags: ['神社仏閣', '街歩き', '和食'],
    bestMonths: [3, 4, 5, 10, 11],
    durationRange: [2, 4],
    fitTravelTypes: ['solo', 'friends', 'couple', 'family'],
    fitPriorities: ['sightseeing', 'gourmet', 'citywalk'],
    fitTravelLoad: ['short', 'flexible'],
    fitBudgetTiers: ['standard', 'luxury'],
    reasonTemplates: {
      base: '定番観光と街歩きのバランスが良く、短めの日程でも満足度を出しやすい旅先です。',
      month: '気候が安定しやすく、散策中心でも過ごしやすい時期です。',
      priority: '歴史ある名所や路地散策が揃い、観光と街歩きの両方を楽しめます。',
    },
  },
  {
    id: 'sapporo',
    name: '札幌',
    country: '日本',
    area: '北海道',
    tags: ['グルメ', '都市', '自然アクセス'],
    bestMonths: [2, 6, 7, 8, 9],
    durationRange: [3, 5],
    fitTravelTypes: ['solo', 'friends', 'family'],
    fitPriorities: ['gourmet', 'citywalk', 'nature'],
    fitTravelLoad: ['flexible'],
    fitBudgetTiers: ['standard', 'luxury'],
    reasonTemplates: {
      base: '都市滞在の快適さと周辺自然へのアクセスを両立しやすい旅先です。',
      month: '旬の食材や過ごしやすい気温が期待しやすい時期です。',
      priority: '海鮮やスイーツの選択肢が豊富で、食を主役にした旅程が組みやすいです。',
    },
  },
  {
    id: 'hakone',
    name: '箱根',
    country: '日本',
    area: '関東',
    tags: ['温泉', '自然', 'リラックス'],
    bestMonths: [1, 2, 3, 4, 10, 11, 12],
    durationRange: [2, 3],
    fitTravelTypes: ['couple', 'family', 'friends'],
    fitPriorities: ['relax', 'nature'],
    fitTravelLoad: ['short'],
    fitBudgetTiers: ['standard', 'luxury'],
    reasonTemplates: {
      base: '移動負荷を抑えながら、温泉と景色でしっかり気分転換しやすい定番エリアです。',
      month: '季節の景色と温泉の組み合わせを楽しみやすいタイミングです。',
      priority: '温泉宿や美術館が点在し、ゆったり過ごす旅に向いています。',
    },
  },
  {
    id: 'okinawa',
    name: '沖縄本島',
    country: '日本',
    area: '沖縄',
    tags: ['海', '自然', 'リゾート'],
    bestMonths: [4, 5, 6, 9, 10],
    durationRange: [3, 6],
    fitTravelTypes: ['friends', 'couple', 'family'],
    fitPriorities: ['nature', 'relax', 'sightseeing'],
    fitTravelLoad: ['flexible'],
    fitBudgetTiers: ['standard', 'luxury'],
    reasonTemplates: {
      base: '海辺の開放感と観光スポットの両方を確保しやすく、非日常感が出しやすい旅先です。',
      month: '海や屋外観光を取り入れやすい季節です。',
      priority: '自然とリラックス要素が強く、ゆるめの旅程でも満足度が出ます。',
    },
  },
  {
    id: 'fukuoka',
    name: '福岡',
    country: '日本',
    area: '九州',
    tags: ['グルメ', '街歩き', '週末旅'],
    bestMonths: [3, 4, 5, 10, 11],
    durationRange: [2, 4],
    fitTravelTypes: ['solo', 'friends', 'couple'],
    fitPriorities: ['gourmet', 'citywalk', 'sightseeing'],
    fitTravelLoad: ['short', 'flexible'],
    fitBudgetTiers: ['budget', 'standard'],
    reasonTemplates: {
      base: 'コンパクトに回りやすく、週末でも旅程が組みやすい都市型の旅先です。',
      month: '街歩きと食べ歩きをバランス良く楽しみやすい時期です。',
      priority: '屋台やローカルグルメを軸にした短期旅行と相性が良いです。',
    },
  },
  {
    id: 'kanazawa',
    name: '金沢',
    country: '日本',
    area: '北陸',
    tags: ['街歩き', '海鮮', '文化'],
    bestMonths: [4, 5, 6, 9, 10, 11],
    durationRange: [2, 4],
    fitTravelTypes: ['solo', 'couple', 'friends'],
    fitPriorities: ['citywalk', 'gourmet', 'sightseeing'],
    fitTravelLoad: ['short', 'flexible'],
    fitBudgetTiers: ['standard', 'luxury'],
    reasonTemplates: {
      base: '歴史地区と食を同時に楽しみやすく、上質寄りの週末旅行にも向いています。',
      month: '散策しやすく、庭園や街並みの魅力を感じやすい季節です。',
      priority: '文化施設や市場がまとまっていて、街歩き中心の旅行を作りやすいです。',
    },
  },
  {
    id: 'ishigaki',
    name: '石垣島',
    country: '日本',
    area: '沖縄',
    tags: ['自然', '離島', 'リラックス'],
    bestMonths: [4, 5, 6, 7, 9, 10],
    durationRange: [4, 6],
    fitTravelTypes: ['couple', 'friends', 'family'],
    fitPriorities: ['nature', 'relax'],
    fitTravelLoad: ['flexible'],
    fitBudgetTiers: ['standard', 'luxury'],
    reasonTemplates: {
      base: '日常から距離を置いた滞在がしやすく、自然の密度を重視する人に向いています。',
      month: '海や離島アクティビティを組み込みやすい時期です。',
      priority: '景色と休息を軸にした、余白のある旅を作りやすいです。',
    },
  },
  {
    id: 'seoul',
    name: 'ソウル',
    country: '韓国',
    area: '東アジア',
    tags: ['近場海外', 'グルメ', 'ショッピング'],
    bestMonths: [3, 4, 5, 9, 10, 11],
    durationRange: [2, 4],
    fitTravelTypes: ['solo', 'friends', 'couple'],
    fitPriorities: ['gourmet', 'citywalk', 'sightseeing'],
    fitTravelLoad: ['flexible'],
    fitBudgetTiers: ['budget', 'standard'],
    reasonTemplates: {
      base: '近場海外の中でも移動しやすく、短期間でも濃い旅程を作りやすい都市です。',
      month: '歩き回りやすく、屋外とショッピングの両方を入れやすい時期です。',
      priority: 'カフェやローカルフードが充実し、街歩きとの相性が良いです。',
    },
  },
  {
    id: 'busan',
    name: '釜山',
    country: '韓国',
    area: '東アジア',
    tags: ['海辺都市', 'グルメ', '近場海外'],
    bestMonths: [4, 5, 6, 9, 10],
    durationRange: [3, 4],
    fitTravelTypes: ['friends', 'couple'],
    fitPriorities: ['gourmet', 'relax', 'citywalk'],
    fitTravelLoad: ['flexible'],
    fitBudgetTiers: ['budget', 'standard'],
    reasonTemplates: {
      base: '海辺の景色と都市滞在を両立しやすく、近場海外として組みやすい旅先です。',
      month: '海沿いの散策や市場巡りが気持ちよくしやすい時期です。',
      priority: '市場グルメと海辺の街歩きをセットで楽しめます。',
    },
  },
  {
    id: 'taipei',
    name: '台北',
    country: '台湾',
    area: '東アジア',
    tags: ['夜市', 'グルメ', '近場海外'],
    bestMonths: [2, 3, 4, 10, 11, 12],
    durationRange: [3, 5],
    fitTravelTypes: ['solo', 'friends', 'couple', 'family'],
    fitPriorities: ['gourmet', 'citywalk', 'relax'],
    fitTravelLoad: ['flexible'],
    fitBudgetTiers: ['budget', 'standard'],
    reasonTemplates: {
      base: '食とローカル感を重視したい人に向いており、初めての近場海外でも回りやすいです。',
      month: '屋外観光と食べ歩きのバランスを取りやすい時期です。',
      priority: '夜市やカフェ巡りを中心に、軽快な旅程を組めます。',
    },
  },
  {
    id: 'kaohsiung',
    name: '高雄',
    country: '台湾',
    area: '東アジア',
    tags: ['港町', 'リラックス', '近場海外'],
    bestMonths: [1, 2, 3, 11, 12],
    durationRange: [3, 5],
    fitTravelTypes: ['couple', 'friends', 'family'],
    fitPriorities: ['relax', 'citywalk', 'gourmet'],
    fitTravelLoad: ['flexible'],
    fitBudgetTiers: ['budget', 'standard'],
    reasonTemplates: {
      base: '台北より落ち着いた空気感で、のんびりした近場海外を探す人に向いています。',
      month: '暑さを避けやすく、散策中心でも回りやすいタイミングです。',
      priority: '港町の空気感を味わいながら、力を抜いた旅を作りやすいです。',
    },
  },
  {
    id: 'jeju',
    name: '済州島',
    country: '韓国',
    area: '東アジア',
    tags: ['自然', 'リゾート', '近場海外'],
    bestMonths: [4, 5, 6, 9, 10],
    durationRange: [3, 5],
    fitTravelTypes: ['couple', 'family', 'friends'],
    fitPriorities: ['nature', 'relax'],
    fitTravelLoad: ['flexible'],
    fitBudgetTiers: ['standard', 'luxury'],
    reasonTemplates: {
      base: 'フライト時間を抑えつつ、自然豊かなリゾート気分を得やすい旅先です。',
      month: '屋外での景観体験が気持ち良く、移動も比較的組みやすい時期です。',
      priority: '自然の風景と余白ある滞在を重視したい人に向いています。',
    },
  },
];
